services:
  pixelaw-core:
    image: ghcr.io/pixelaw/core:0.1.28
    platform: linux/x86_64
    container_name: pixelaw-core
    environment:
      - DISABLE_FEE=true
      - DISABLE_VALIDATE=true
    ports:
      - "127.0.0.1:5050:5050"
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:9090:9090"
    restart: unless-stopped
    networks:
      - pixelaw
    volumes:
      - storage:/keiko/storage
      - log:/keiko/log
networks:
  pixelaw:
    driver: bridge
volumes:
  storage:
  log:
