services:
  pixelaw-core:
    image: oostvoort/pixelaw-core:v0.0.23
    container_name: pixelaw-core
    ports:
      - "5050:5050"
      - "3000:3000"
      - "8080:8080"
      - "50051"
    restart: unless-stopped
    networks:
      - pixelaw
    environment:
      - INVOKE_MAX_STEPS=4000000

networks:
  pixelaw:
    driver: bridge

