
[package]
cairo-version = "=2.10.1"
name = "sequential_1_dense_3_matmul_readvariableop_0"
version = "0.1.0"
edition = "2024_07"

[dependencies]
orion = { git = "https://github.com/gizatechxyz/orion.git", rev = "v0.1.9" }
    