[world]
description = "Empty PixeLAW world"
name = "maze"
seed = "pixelaw"

[namespace]
default = "pixelaw"
mappings = {}

[env]
rpc_url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_7"
keystore_path = "accounts/sepolia.deployer.keystore.json"
world_address = "0x2bf4d3aa0dced89d37d8c3b4ff6a05895c0af32ff3baf9b02abf8504e53eaad"

account_address = "YOUR_ACCOUNT"