[package]
cairo-version = "=2.10.1"
name = "maze"
version = "0.0.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[dependencies]
pixelaw = { git = "https://github.com/pixelaw/core", branch = "player_fix" }
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.6.2" }
#pixelaw = { path = "../core/contracts" }

[dev-dependencies]
pixelaw_testing = { git = "https://github.com/pixelaw/core", branch = "player_fix" }
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.6.2" }
#pixelaw_testing = { path = "../core/pixelaw_testing" }

[[target.starknet-contract]]
sierra = true

build-external-contracts = [
  "dojo::world::world_contract::world",
  "pixelaw::core::models::pixel::m_Pixel",
  "pixelaw::core::models::area::m_Area",
  "pixelaw::core::models::queue::m_QueueItem",
  "pixelaw::core::models::registry::m_App",
  "pixelaw::core::models::registry::m_AppName",
  "pixelaw::core::models::registry::m_CoreActionsAddress",
  "pixelaw::core::models::area::m_RTree",
  "pixelaw::apps::player::m_Player",
  "pixelaw::apps::player::m_PositionPlayer",
  "pixelaw::apps::house::m_House",
  "pixelaw::apps::house::m_PlayerHouse",
  "pixelaw::apps::snake::m_Snake",
  "pixelaw::apps::snake::m_SnakeSegment",
  "pixelaw::core::events::e_QueueScheduled",
  "pixelaw::core::events::e_Notification",
  "pixelaw::core::actions::actions",
  "pixelaw::apps::paint::paint_actions",
  "pixelaw::apps::snake::snake_actions",
  "pixelaw::apps::player::player_actions",
  "pixelaw::apps::house::house_actions",
]

[tool.fmt]
sort-module-level-items = true


[profile.sepolia]
