[world]
name = "pixelaw"
description = "PixeLAW PIX2048 Game"
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/pixelaw/examples"
socials.x = "https://twitter.com/pixelaw"

[namespace]
default = "pix2048"

[[namespace.mappings]]
namespace = "pix2048"
account = "$DOJO_ACCOUNT_ADDRESS"