[package]
cairo-version = "=2.9.2"
name = "rps"
version = "0.0.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[[target.starknet-contract]]
sierra = true
build-external-contracts = ["dojo::world::world_contract::world"]


[dependencies]
starknet = "=2.9.2"
pixelaw = { git = "https://github.com/pixelaw/core", tag = "v0.6.13" }
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.2.1" }


[scripts]
init = "sozo execute --wait pixelaw-rps_actions init "