# How to use this config file: https://book.dojoengine.org/framework/config#dojo_profiletoml

[world]
name = "chest"
seed = "pixelaw"

[namespace]
default = "chest"
# Reserve the pixelaw core contract names, the rest can be "chest" automatically.
mappings = { "pixelaw" = [
    "actions", "App", "AppName", "Area", "CoreActionsAddress", "Pixel", "QueueItem", "RTree", "Notification", "QueueScheduled"
] }

[env]
rpc_url = "http://localhost:5050/"
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"
world_address = "0x01d09b5e00f376337603943fc12715e439e91c0039f353b1cc48bb278dfa99d5"

[writers]
"chest-ClickGame" = ["chest-chest_actions"]